# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bridge Roots
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/cassielawfirm" # the subpath of your site, e.g. /blog
url: "http://beta.catenology.com" # the base hostname & protocol for your site
# url: "http://127.0.0.1:4000" # test use
collections:
  services:
    output: false
  members:
      output: true
  branchs:
      output: true

# Build settings
markdown: kramdown
